spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/wingterview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://prod-rds-az1.c7yeqiwak4u9.ap-northeast-2.rds.amazonaws.com:3306/wingterview?useUnicode=true&character_set_server=utf8mb4&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: application-secret.yml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

rabbitmq:
  queue:
    name: ai.request.queue
  exchange:
    name: ai.request.exchange
  routing:
    key : ai.request.single

#  redis:
#    host: localhost
#    port: 6379
      
oauth:
  kakao:
    token-request-uri: https://kauth.kakao.com/oauth/token
    token-info-uri: https://kapi.kakao.com/v1/user/access_token_info
#    redirect-uri: https://dev.s3.wingterview.com/auth/kakao
#    redirect-uri: http://localhost:5173/auth/kakao
#    redirect-uri: http://wingterview.com/auth/kakao
    redirect-uri: https://wingterview.com/auth/kakao
    client-id: ${OAUTH_KAKAO_CLIENT_ID}

ai:
  follow-up-url: https://ai.wingterview.com/interview/followup-questions
  api-key: ${AI_API_KEY}
  api-url: ${AI_API_URL}

cloud:
  aws:
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}

  credentials:
    access-key: ${CLOUD_CREDENTIALS_ACCESS_KEY}
    secret-key: ${CLOUD_CREDENTIALS_SECRET_KEY}
    stack:
      auto: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
