spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wingterview?useUnicode=true&character_set_server=utf8mb4&serverTimezone=Asia/Seoul
    username: root
    password: wingter12!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: localhost
    port: 6379
      
      
oauth:
  kakao:
    token-request-uri: https://kauth.kakao.com/oauth/token
    token-info-uri: https://kapi.kakao.com/v1/user/access_token_info
    client-id: ef80aa676a39c68abe9ada569d9ab70b
    redirect-uri: http://localhost:8080/api/auth/oauth/kakao/callback
