name: Block Protected File Changes

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'wingterview/src/main/resources/application.yml'
      - 'wingterview/src/main/java/com/easyterview/wingterview/config/CorsConfig.java'
      - 'wingterview/Dockerfile'
      - 'wingterview/build.gradle'

jobs:
  block-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel PR if protected files changed
        run: |
          echo " Protected config files were modified in this PR."
          exit 1
